language: objective-c  #1
osx_image: xcode9.2 #2
xcode_project: DrX.xcodeproj #3
xcode_scheme: DrX #4
xcode_sdk: iphonesimulator11.2

before_install:
  - brew install carthage

install:
  - carthage update

script: 
  - xcodebuild -project DrX.xcodeproj -scheme DrX -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - xcodebuild test -project DrX.xcodeproj -scheme DrX -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.1' -sdk iphonesimulator
