name: Swift Package Manager

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=15.0,name=iPhone 13']
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test 
